### ISSUE TITLE
'yarn test' fails, missing @nestjs/platform-express

### ISSUE THREAD

**Issue by jleverenz** [nest-modules/ioredis#261]
```
% yarn test
yarn run v1.22.19
$ jest
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfig" is deprecated, use "[jest-config].globals.ts-jest.tsconfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
[Nest] 15512   - 03/15/2023, 8:58:33 AM   [ExceptionHandler] The "@nestjs/platform-express" package is missing. Please, make sure to install this library ($ npm install @nestjs/platform-express) to take advantage of NestFactory.
  ●  process.exit called with "1"

      19 |     }).compile();
      20 |
    > 21 |     const app = module.createNestApplication();
         |                            ^
      22 |     await app.init();
      23 |     const redisModule = module.get(RedisModule);
      24 |     expect(redisModule).toBeInstanceOf(RedisModule);

      at Object.loadPackage (../node_modules/@nestjs/common/utils/load-package.util.js:13:17)
      at TestingModule.createHttpAdapter (../node_modules/@nestjs/testing/testing-module.js:25:56)
      at TestingModule.createNestApplication (../node_modules/@nestjs/testing/testing-module.js:13:43)
      at redis.module.spec.ts:21:28
      at fulfilled (../node_modules/tslib/tslib.js:114:62)

 RUNS  lib/redis.module.spec.ts
error Command failed with exit code 1.
```

Installing the missing package resolves the error, but I'm running into additional problems after that. Want to confirm I'm not missing something before continuing..

**Comment by juandav** [comment]
DONE
