### ISSUE TITLE
Impossible to mock in unit tests

### ISSUE THREAD

**Issue by MFrat** [nest-modules/ioredis#286]
It is not possible to mock `@InjectRedis() private readonly redis: Redis` in unit tests. The following error occurs:
```
ENOENT: no such file or directory, open 'node:child_process'

      at Runtime.readFile (node_modules/jest-runtime/build/index.js:1987:21)
      at Object.<anonymous> (node_modules/check-disk-space/dist/check-disk-space.cjs:5:26)
```

**Comment by jleverenz** [comment]
You might need to provide some additional context, like what you've tried in your unit test. I've setup a pattern along these lines with some success:

```
import { Test } from '@nestjs/testing';
import { getRedisConnectionToken } from '@nestjs-modules/ioredis';

describe('YourService', () => {
  const redisMock = {}; // replace with your mock

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      providers: [
        {
          provide: getRedisConnectionToken(),
          useValue: redisMock,
        },
        YourService,
      ],
    }).compile();
  });
  // ...
});
```
